version: '3'

services:
  # データベース
  db:
    build: ./db
    container_name: pyground_db
    ports:
      - 5432:5432
    environment:
        - POSTGRES_USER=testuser
        - POSTGRES_PASSWORD=test
        - PGPASSWORD=test
        - POSTGRES_DB=django
        - DATABASE_HOST=localhost
    volumes:
        - ./db/pgdata:/var/lib/postgresql/data

  # Djangoアプリ
  web:
    build: ./web
    container_name: pyground_web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/code
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db
