# Generated by Django 3.1.5 on 2021-01-25 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='問題名')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('question_answer', models.TextField(verbose_name='答え')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='対象ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Correcter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('correct_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='対象ユーザー')),
                ('target_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question', verbose_name='対象問題')),
            ],
        ),
    ]
