# Generated by Django 3.1.5 on 2021-01-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='question_input',
            field=models.TextField(default='', verbose_name='入力'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_output',
            field=models.TextField(default='', verbose_name='出力'),
        ),
    ]
