# Generated by Django 3.1.5 on 2021-01-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210125_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default_code',
            field=models.TextField(default='', verbose_name='コード'),
        ),
    ]
