# Generated by Django 3.1.5 on 2021-01-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='create_at',
        ),
        migrations.AddField(
            model_name='follow',
            name='udpate_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='permit',
            name='udpate_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
