# Generated by Django 3.1.5 on 2021-01-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_icon',
            field=models.ImageField(blank=True, default='user_icon/user_icon.png', upload_to='user_icon/', verbose_name='ユーザーアイコン'),
        ),
    ]
