# Generated by Django 3.1.5 on 2021-01-25 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='対象コード')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='対象ユーザー')),
            ],
        ),
    ]
