# Generated by Django 3.1.5 on 2021-01-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20210125_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='create_at',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
